USE dates;

DROP PROCEDURE IF EXISTS TASK4;
DELIMITER //
CREATE PROCEDURE TASK4 (IN start_day DATE)
	BEGIN
		DECLARE i INT DEFAULT 0;
		WHILE I < 31 DO
			INSERT INTO test (created_at) VALUES (DATE_ADD(start_day, INTERVAL i DAY));
			SET i = i + 1;
		END WHILE;		
	END
//

CALL TASK4 ('2021-05-01');
DELIMITER ;
SELECT * FROM test;
DELIMITER //
CREATE PROCEDURE DELETE_ROWS (IN num INT)
	BEGIN
		DECLARE i INT DEFAULT (SELECT COUNT(*) FROM test);
		WHILE i > num DO
			DELETE FROM test ORDER BY created_at LIMIT 1;
			SET i = i - 1;
		END WHILE;
	END
//
CALL DELETE_ROWS (5);
DELIMITER ;
SELECT * FROM test;
